### ISSUE TITLE
Dropdown for "other projects" closing unexpectedly

### ISSUE THREAD

**Issue by LandonMarshall** [theserverproject/BaseSite#28]
MacOS Mojave 10.14.4
Chrome Version 76.0.3809.132 (Official Build) (64-bit)

The dropdown opens when clicked on but when I try to navigate to an item in the dropdown, the menu closes

**Comment by LandonMarshall** [comment]
This issue will be fixed when min-height for navbar is added

**Comment by Ross-Alexandra** [comment]
This ticket is a problem caused by Chrome not obeying the 'height' value provided in the css. Once that's fixed, the stylistic issues and functional issue described here will be resolved.

**Comment by LandonMarshall** [comment]
Taking out ```height: 100vh```
in the page-content seems to fix this and the white space below the footer
