### ISSUE TITLE
Spelling mistakes/ Typos

### ISSUE THREAD

**Issue by LandonMarshall** [theserverproject/BaseSite#29]
Proper spelling - Scalability

3rd paragraph on main page

**Comment by LandonMarshall** [comment]
Also - same sentence, period should be outside of closing bracket.

**Comment by LandonMarshall** [comment]
Also, end of second paragraph, there is no period

**Comment by LandonMarshall** [comment]
Also, beginning of second paragraph, its -> it's

**Comment by LandonMarshall** [comment]
Also, 
"with interests in creating scaleable, sustainable, functional software, and machine learning"
made me have to go back and read it twice to understand - could be worded differently (the and machine learning is throwing me off I think)

**Comment by Ross-Alexandra** [comment]
'ML' is a programming language, change to 'machine learning'

**Comment by LandonMarshall** [comment]
I more so meant the list seperated by commas following another interest was hard to read
